name: app_framework
description: 
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  path_provider:
  device_info_plus:
  flutter_image_compress: ^2.1.0
  image_pickers: ^2.0.4+8
  image_picker: ^1.0.7
  package_info_plus: ^5.0.1
  http: ^1.2.0
  shared_preferences: ^2.2.2



  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

